AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Lint/ToJSON:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/OptionalBooleanParameter:
  AllowedMethods: ['as_xml']
Style/SymbolProc:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
